### ISSUE TITLE
Chime control 

### ISSUE THREAD

**Issue by LuisDiazUgena** [PricelessToolkit/ESPBell-LITE#12]
Hi!

I was wondering if there is a possibility to "mute" the chime.  The idea is to be able to mute or unmute the chime and still being able to recieve notifications.

Does the doorbell sense require a chime to be used to detect that the button has been pressed? If not, it might be ok to just detect the button press, then route the signal.

**Comment by PricelessToolkit** [comment]
You can unscrew one contact from chime. espbell doesnot recuire chime, only power supply and button.

**Comment by LuisDiazUgena** [comment]
I could wire up the chime trough a relay and use one of the gpio available
to power on and off the chime, right?

**Comment by LuisDiazUgena** [comment]
Thanks. Already have some relay boards, with octocouplers and aldo an ssr in my electronic stash.

What I'm not sure is how to wire it. The chime sound in my model is played through the headset itself I think. If i unolug the headset no chime sound is played if the button is been pressed, but I also have a regular chime. I need to check the wiring.

I need to do some testing but I think this project will be great to add this feature to my smart home.

(For some background, i have a 1 year old son who sometimes sleeps really bad 🤣)

**Comment by PricelessToolkit** [comment]
I don't use chime, disabled it completely. HA sound notification + WLED notification is enough, also disabling and enabling it is easier.
