### ISSUE TITLE
CPL file missing

### ISSUE THREAD

**Issue by niddey** [PricelessToolkit/ESPBell-LITE#7]
Can you provide the PCB CPL / Centroid file so if one wants they could order the pcbs from pcbway pre done?

**Comment by PricelessToolkit** [comment]
Hi, Sorry, but I don't provide the PCB CPL/Centroid files for assembly. You can find pre-assembled boards in my shop though. If you're up for some DIY, all the files you need are on GitHub. You can order a blank PCB and the components, then solder them yourself. I'm trying to avoid having these boards show up on sites like Ali. Hope that works for you!
