### ISSUE TITLE
QwikBUS System(STR HT3033) supported?

### ISSUE THREAD

**Issue by eikaramba** [PricelessToolkit/ESPBell-LITE#8]
Hey there, i have the following intercom:

STR HT3033
Picture available from the internet here: https://www.elt24.de/shop/STR-33301W-QwikBUS-Haustelefon-HT3033-weiss

For me it seems that this is not a 4+n System but a 1+n system or maybe even something in between.

Luckily a german hacker space did wrote an article and was able to put a esp on it.
https://wiki-hackerspace--bremen-de.translate.goog/sonstiges/tuerklingel?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=wapp

However it seems to be a little complicated. so from the article i understand i can listen to the ringing event on pin 6. but to actually trigger the door i would need to directly solder the espbell to basically the mechanical switch which i would normally press to open the door right? i wanted to kindly ask if you think so too before i waste any time with it :)

BTW: Incredible nice project of yours!

**Comment by PricelessToolkit** [comment]
Hi, if the data from this article is correct then you need to connect one leed of optocoupler to pin 2 second to pin 6. Relay wires to the "button legs/contacts"

**Comment by eikaramba** [comment]
thanks for that quick reply. i will try that closing for now and reopen if there are any problems.

**Comment by LukasBombach** [comment]
Hey @eikaramba I am curios, did it work? I have a Qwikbus system too (one with video) and all commericial solution failed so far. Did you manage to get this one working?

**Comment by eikaramba** [comment]
hey @LukasBombach unfortunately i never got the time to try it. i still plan to maybe do this at some point but for now my smart home stays dump in that regard ;)
